version: '3'
services:
  app:
    build: .
    depends_on:
      - db
    volumes:
      - ./lib:/app/lib
      - ./config:/app/config
      - ./priv:/app/priv
      - build:/app/_build
      - deps:/app/deps
    ports:
      - 4000:4000
  db:
    image: postgres
    volumes:
      - 'db:/var/lib/postgres/data'

volumes:
  build:
  deps:
  db:
